### ISSUE TITLE
Typoes of CCA_###

### ISSUE THREAD

**Issue by ShawnLess** [riscv/docs-dev-guide#22]
The cache coherence ID 'CCA_010' and 'CCA_020' should be 'CCS_010' and 'CCS_020', to align with other IDs.

**Comment by wmat** [comment]
Can point me at where these typos are?  I can't seem to find them in the Docs Dev Guide.

**Comment by ShawnLess** [comment]
Hi Bill, I'm really sorry, posted in wrong repo.
