### ISSUE TITLE
Precommit keeps failing

### ISSUE THREAD

**Issue by kersten1** [riscv/docs-dev-guide#36]
@kbroch-rivosinc the precommit in this repo is failing. Not sure why. When you get a free minute, can you diagnose? But not top priority - I can keep ignoring...

**Comment by kbroch-rivosinc** [comment]
just looks like someone didn't install `pre-commit install`  and therefore made commit(s) without running the checks.
I should probably document that in this repo for contributors, for now here's the link to it: https://github.com/riscv/docs-spec-template?tab=readme-ov-file#enabling-pre-commit-checks-locally
